server:
  port: 8080
spring:
  application:
    name: checkgame
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/checkgame
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  #security:
  #  user:
  #    name: root
  #    password: root